site_name: Jasonette
google_analytics: ['UA-54282166-8', 'auto']
pages: 
- ■ Getting started: index.md
- ■ iOS: ios.md
- ■ Android: android.md
- ■ Examples: examples.md
#- Reference: reference.md
- ■ Reference:
  - ★ View: document.md
  - ★ Link: href.md
  - ★ Actions: actions.md
  - ★ Components: components.md
#  - Interaction: interaction.md
  - ★ Layout: layout.md
  - ★ Templates: templates.md
  - ★ Mix-in: mixin.md
  - ★ Offline: offline.md
  - ★ Agents: agents.md
  - ★ Web Container: web.md
  - ★ Environment Variables: env.md
- ■ Tips: convention.md
- ■ Extending Jasonette (advanced): advanced.md
- ■ Troubleshoot: faq.md
- ■ Jason: jason.md
theme: readthedocs
#theme: simplex
#theme: flatly
repo_url: https://github.com/Jasonette/documentation
